services:
  vitom-be:
    build:
      context: ./Vitom-BE
      dockerfile: Dockerfile
    container_name: vitom_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - 8080:8080
    depends_on:
      seq:
        condition: service_started
        restart: true
      postgres_db:
        condition: service_started
        restart: true

  vitom-fe:
    build:
      context: ./Vitom-FE
      dockerfile: Dockerfile
    volumes:
      - ../../packages/dashboard:/app
    ports:
      - 80:80
    depends_on:
      postgres_db:
        condition: service_started
        restart: true
      seq:
        condition: service_started
        restart: true

  postgres_db:
    container_name: postgres_container
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=VitomDB
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: thinhdpham2510@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Ph@mDucThinh25102003
    ports:
      - 8090:80
    depends_on:
      postgres_db:
        condition: service_started
        restart: true
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  seq:
    image: datalust/seq:latest
    container_name: app-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8089:80

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
volumes:
  data:
